# Generated by Django 2.1 on 2019-02-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
