# Generated by Django 2.1 on 2019-02-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
