# Generated by Django 2.1 on 2019-02-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='count',
            new_name='post_hit',
        ),
    ]
